### ISSUE TITLE
Ventura support?

### ISSUE THREAD

**Issue by Jan-E** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#25]
Quote from the 082.1 Changelog:
>Tested successfully with macOS Catalina to macOS Ventura

Ventura would be really awesome!

What did you use as csr-active-config for Ventura? The same as for Monterey? Was it a clean install of Ventura or an upgrade from Monterey?

Thanks. Keep up the good work.

**Comment by 5T33Z0** [comment]
I won't provice a Guide for installing macOS Ventura since it's rather complicated and there are no graphics drivers available – and probably won't ever. I followed this guide (Option 1) for testing: https://forums.macrumors.com/threads/oc-ventura-install-on-cmp-5-1.2347310/?post=31172042#post-31172042

Don't update from Monterey because iof the driver situation

Ventura uses a 12 bit bitmaske for csr-active-config as Big Sur and newer. I used 67080000

**Comment by Jan-E** [comment]
OK, thanx for the pointer to the Macrumors thread.

**Comment by Jan-E** [comment]
Looks like the OpenCore Legacy Patcher devs have tackled the graphics support on Ivy Bridge (HD4000):
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/1008
Are you working on a Ventura version now?

**Comment by 5T33Z0** [comment]
Thanks for the heads-up. This notebook performs worse with anything newer than Catalina, so I won't upgrade past that. But I maybe test if the EFI works with ventura on a different disk

**Comment by Jan-E** [comment]
I am using Monterey on another Ivy Bridge/HD4000 machine for quite some time now: the X230t. Right now Monterey is the minimum requirement for developing with the latest Xcode, but in a few months Ventura will be required. So I am really interested to see if it can work now. My SSD already has 3 partitions with macOS (Catalina, Big Sur, Monterey). I can easily drop either Catalina and Big Sur to make room for Ventura. I did not boot into one of those 2 for a coule of months now.

**Comment by 5T33Z0** [comment]
I'm getting really annoyed with Apple releaseing a new version of macOS each year instead of finishing one so that it just works flawlessly. Worst thing about it is that they are using it to force users to upgrade their software and hardware ultinmately. I am using Logic Pro and every few versions you are forced to upgrade the OS otherwise you can't use the latest version. And if you ask me it's not because it uses features which are not supported by the OS itself :D

**Comment by 5T33Z0** [comment]
![Ventura_Proof](https://user-images.githubusercontent.com/76865553/207999617-ff1799ac-adf2-40d2-9306-a9eac3c19cd9.png)

Instructions later…

**Comment by Jan-E** [comment]
> I'm getting really annoyed with Apple releaseing a new version of macOS each year instead of finishing one so that it just works flawlessly. Worst thing about it is that they are using it to force users to upgrade their software and hardware ultinmately. I am using Logic Pro and every few versions you are forced to upgrade the OS otherwise you can't use the latest version. And if you ask me it's not because it uses features which are not supported by the OS itself :D

Almost there: Xcode 14.3 beta requires Ventura
